version: '3.9'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Roro
      POSTGRES_DB: digit_logs
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  streamlit:
    build: ./app
    depends_on:
      - db
    ports:
      - "8501:8501"
    environment:
      - DB_HOST=db
      - DB_NAME=digit_logs
      - DB_USER=postgres
      - DB_PASSWORD=Roro

volumes:
  db_data:
